name: CI

on:
  push:
    branches: ["main"]
  pull_request_review:
    types: [submitted]
  workflow_dispatch: {}

jobs:
  test:
    if: ${{ github.event_name == 'push' || github.event.pull_request.base.ref == 'main' }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        rust: [stable]
        include:
          - os: ubuntu-latest
            rust: stable

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v5
      #  with:
      #    lfs: true
      - uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: ${{ matrix.rust }}
      - uses: Swatinem/rust-cache@v2
      - run: cargo check --all-features --all-targets
      - run: cargo test 'smoke_tests::' --all-features
      - run: cargo test 'write_tests::' --all-features
      - run: cargo test 'memory_optimized_read_tests::' --all-features
      - run: cargo test 'speed_optimized_read_tests::' --all-features

  msrv:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: 1.89.0
      - uses: Swatinem/rust-cache@v2
      - run: cargo check --all-features

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable
          components: rustfmt, clippy
      - uses: Swatinem/rust-cache@v2
      - run: cargo fmt --all -- --check
      - run: cargo clippy --all-targets --all-features -- -W warnings

  #ToDo
  #audit:
  #  runs-on: ubuntu-latest
  #  steps:
  #  - uses: actions/checkout@v5
  #  - uses: EmbarkStudios/cargo-deny-action@v2
